export const employeeConstants = {
  GET_EMPLOYEE_WORK_REQUEST: 'GET_EMPLOYEE_WORK_REQUEST',
  GET_EMPLOYEE_WORK_SUCCESS: 'GET_EMPLOYEE_WORK_SUCCESS',
  GET_EMPLOYEE_WORK_FAILURE: 'GET_EMPLOYEE_WORK_FAILURE',
}
